#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 I II
bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a code desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a whatsdesk desktop='^4'
bspc rule -a spotify desktop='^5'
bspc-rule -a pcsx2-qt desktop='^6'
bspc rule -a Archmain state=floating
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


#Autostart Apps

killall -q polybar
#polybar -q main -c /home/Padilla/.config/polybar/forest/config.ini & 
polybar -conf /home/Padilla/.config/polybar/config.ini &
sxhkd &
picom --config /home/Padilla/.config/picom-bspwm.conf &
setxkbmap es
dunst -config /home/Padilla/.config/dunstrc &
nitrogen --restore
